export const SET_NAVIGATION = 'SET_NAVIGATION';

export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';

export const SET_LEVEL_UPLOAD = 'SET_LEVEL_UPLOAD';
export const SET_PHOTO_UPLOAD = 'SET_PHOTO_UPLOAD';

export const SET_USER = 'SET_USER';
export const ON_UPLOAD_PHOTO = 'ON_UPLOAD_PHOTO';
export const GET_MAIN_PHOTO_LIST = 'GET_MAIN_PHOTO_LIST';
