export const SET_NAVIGATION = 'SET_NAVIGATION';

export const SET_SELECTED_PRODUCT = 'SET_SELECTED_PRODUCT';

export const SET_LEVEL_UPLOAD = 'SET_LEVEL_UPLOAD';
export const SET_PHOTO_UPLOAD = 'SET_PHOTO_UPLOAD'; 